paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220616_HeLaCISD2_roGFP\\cyto\\Quantification"
  calibrated: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220616_HeLaCISD2_roGFP\\cyto\\Calibrated"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220616_HeLaCISD2_roGFP\\cyto\\Calibrated"
constants:
  min_start_time: 945
  min_end_time: 1410
  max_start_time: 620
  max_end_time: 945
# write null if you want to execute the script for all data files in your path
filename: "KO_CTRL_1.nd2 - C=0_ratio.xlsx"
