paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210416-TrexCISD2-FURA-ER-store\\Calibration"
  calibrated: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210416-TrexCISD2-FURA-ER-store\\Calibration\\Calibrated"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210416-TrexCISD2-FURA-ER-store\\Calibration\\Calibrated"
constants:
  min_start_time: 285
  min_end_time: 305
  max_start_time: 383
  max_end_time: 446
# write null if you want to exectute the script for all data files in your path
filename: "CISD2_1.xlsx"
