paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Quantification"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Traces"
filename: Null
sheetname: "Sheet1"
