paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230413 HeLa Zerihun CISD2 Bcl2 store content\\Traces"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230413 HeLa Zerihun CISD2 Bcl2 store content\\Quantification\\TG_response"
constants:
  baseline_start_time: 78
  baseline_end_time: 98
  response_start_time: 98
  response_end_time: 698
filename: "Bcl2_CISD2_1.nd2 - ratio.xlsx"
sheetname: "FURA"
ID: "20210624_KO_3"
