paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210624_HeLaCISD2_FURA_RmtCEPIA3_storecontent\\Quantification"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210624_HeLaCISD2_FURA_RmtCEPIA3_storecontent\\Quantification\\TG_response"
constants:
  baseline_start_time: 78
  baseline_end_time: 98
  response_start_time: 98
  response_end_time: 698
filename: "KO_3.xlsx"
sheetname: "FURA"
ID: "20210624_KO_3"
