paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\F_over_F0"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211109_HeLaCISD2_SOCE\\Quantification\\Results\\F4"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 80
  baseline_end_time: 100
  osc_start_time: 285
  osc_end_time: 465
# write null if you want to execute the script for all data files in your path
filename: "KO_1.nd2 - C=0_F4_raw_F_over_F0.xlsx"
sheetname: "Sheet1"
Genotype: "CISD2 KO"
Dose: "100"
ID: "20211119_KO_1"
