paths:
  data: "C:\\Users\\jensl\\Box\\PhD\\Data\\NIKON\\20220401_HeLaCISD2_test_roGFP\\Calibrated"
  osc: "C:\\Users\\jensl\\Box\\PhD\\Data\\NIKON\\20220401_HeLaCISD2_test_roGFP\\Results"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 50
  baseline_end_time: 60
  osc_start_time: 60
  osc_end_time: 70
# write null if you want to execute the script for all data files in your path
filename: "KO_3.nd2 - C=0_ratio_calibrated.xlsx"
sheetname: "Sheet1"
Genotype: "CISD2"
Dose: "1"
ID: "20220401_KO_3"
