paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220505_HeLaCISD2_mtCEPIA_recomp\\F_over_F0"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220505_HeLaCISD2_mtCEPIA_recomp\\Quantification\\Results\\F4"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 80
  baseline_end_time: 100
  osc_start_time: 280
  osc_end_time: 460
# write null if you want to execute the script for all data files in your path
filename: "KO_EV_2.nd2 - C=0_F4_raw_F_over_F0.xlsx"
sheetname: "Sheet1"
Genotype: "CISD2 KO_EV"
Dose: "100"
ID: "20220505_EV_2"