paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Calibrated"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Quantification\\Results"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 100
  baseline_end_time: 120
  osc_start_time: 120
  osc_end_time: 140
# write null if you want to execute the script for all data files in your path
filename: "cyto_KO_1.nd2 - C=0_ratio_calibrated.xlsx"
sheetname: "Sheet1"
Genotype: "CISD2 KO"
Dose: "1"
ID: "202200408_KO_1"
