paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\F_over_F0"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\Quantification\\Results\\mtCEPIA"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 70
  baseline_end_time: 90
  osc_start_time: 284
  osc_end_time: 464
# write null if you want to execute the script for all data files in your path
filename: "WT_5.nd2 - C=1_mtCEPIA_raw_F_over_F0.xlsx"
sheetname: "Sheet1"
Genotype: "WT"
Dose: "100"
ID: "20211119_WT_5"
