paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220915_HeLaCISD2_mtCEPIA_mutants\\F_over_F0"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220915_HeLaCISD2_mtCEPIA_mutants\\Results\\F4"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 120
  baseline_end_time: 140
  osc_start_time: 144
  osc_end_time: 324
# write null if you want to execute the script for all data files in your path
filename: "EV_3.nd2 - C=0_F4_raw_F_over_F0.xlsx"
sheetname: "FF0_resp"
Genotype: "CISD2 KO_EV"
Dose: "5"
ID: "20220915_KO_EV_3"
