paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210507-TrexCISD2-oscillations-FURA\\Quantification"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210507-TrexCISD2-oscillations-FURA\\Quantification\\0Ca"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.02
  peak_threshold: 0.02
  baseline_start_time: 340
  baseline_end_time: 360
  osc_start_time: 195
  osc_end_time: 345
# write null if you want to execute the script for all data files in your path
filename: "KO_3_340_Results_ratio.xlsx"
sheetname: "Sheet1"
Genotype: "KO"
Dose: 0
ID: "20210507_KO_3"
