paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220210_HeLaCISD2_Bcl2\\Quantification"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220210_HeLaCISD2_Bcl2\\Quantification\\Results\\ATP"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 70
  baseline_end_time: 90
  osc_start_time: 90
  osc_end_time: 210
# write null if you want to execute the script for all data files in your path
filename: "WT_EV_3.nd2 - C=0_raw_F_over_F0.xlsx"
sheetname: "FF0_resp"
Genotype: "CISD2_mCherry"
Dose: "0.3"
ID: "20220210_CISD2_mCherry_3"
