paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210520-HeLaCISD2-FURA-Bcl2\\Calibration\\Calibrated"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210520-HeLaCISD2-FURA-Bcl2\\Quantification"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 5
  peak_threshold: 5
  basal_start_time: 20
  basal_end_time: 50
  baseline_start_time: 130
  baseline_end_time: 160
  osc_start_time: 162
  osc_end_time: 282
# write null if you want to execute the script for all data files in your path
filename: "KO_BCL2_1_calibrated.xlsx"
sheetname: "Sheet1"
Genotype: "KO"
Dose: "Bcl-2"
ID: "20210520_KO_BCL2_1"
