paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210513-HeLaCISD2-F4-RmtCEPIA3\\Quantification"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210513-HeLaCISD2-F4-RmtCEPIA3\\Quantification\\F4"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.04
  peak_threshold: 0.02
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 270
  baseline_end_time: 280
  osc_start_time: 462
  osc_end_time: 642
# write null if you want to execute the script for all data files in your path
filename: "WT_1.xlsx"
sheetname: "F4_FF0_resp"
Genotype: "WT"
Dose: "100"
ID: "20210513_WT_1"
