paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210218_HeLa_Fura_ATP_RITA\\Calibrated"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210218_HeLa_Fura_ATP_RITA\\Quantification"
constants:
  smoothing_constant: 6
  stdev_non-oscillating: 5
  peak_threshold: 10
  baseline_start_time: 40
  baseline_end_time: 50
  osc_start_time: 58
  osc_end_time: 148
# write null if you want to execute the script for all data files in your path
filename: "20210218_WT_EV_ATP_2 analysis_calibrated.xlsx"
sheetname: "Quantify"
