paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\FDSS\\Robbe"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\FDSS\\Robbe"
constants:
  baseline_start_time: 40
  baseline_end_time: 60
  start_time: 60
  end_time: 540
  acquisition_time_interval: 1
  rate_duration: 10









  
