paths:
  data: "J:\\GBW-0051_IP3 Group\\Jens\\20230313_workshop\\FURA mCherry\\Traces"
  results: "J:\\GBW-0051_IP3 Group\\Jens\\20230313_workshop\\FURA mCherry\\Results"
constants:
  smoothing_constant: 4
  stdev_non-oscillating: 0.05
  peak_threshold: 0.2
  basal_start_time: 5
  basal_end_time: 25
  baseline_start_time: 80
  baseline_end_time: 100
  osc_start_time: 104
  osc_end_time: 224
# write null if you want to execute the script for all data files in your path
filename: "mCherry.nd2 - ratio.xlsx"
sheetname: "Sheet1"
Genotype: "mCherry"
Dose: "2µM_ATP"
ID: "20230313_mCherry_1"
