paths:
  data: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\NIKON\\20210930_HeLa_CISD2_F4mtCEPIA_10uM"
  time: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\NIKON\\20210930_HeLa_CISD2_F4mtCEPIA_10uM\\Time"
