paths:
  data: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\NIKON\\20210624_HeLaCISD2_troubleshootmcherry"
  time: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\NIKON\\20210624_HeLaCISD2_troubleshootmcherry\\Time"
