paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210325-HeLaCISD2-F4-RmtCEPIA3\\Quantification"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210325-HeLaCISD2-F4-RmtCEPIA3\\Quantification\\F4-response"
constants:
  smoothing_constant: 4
  stdev_non_oscillating_trace: 0.0008
  peak_threshold: 0.1
  baseline_start: 80
  baseline_end: 100
  concentrations: [5, 100]
  concentration_start: [135, 310]
  concentration_end: [255, 430]
filename: "20210325-KO1-CISD2.xlsx"
sheetname: "fluo4_FF0"

