paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\Quantification"
  F0: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\F_over_F0"
constants:
  F0_start_time: 60
  F0_end_time: 80
# write null if you want to execute the script for all data files in your path
filename: "WT_4.nd2 - C=1_mtCEPIA_raw.xlsx"
sheetname: "Sheet1"