paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211008_HeLa_CISD2_mtCEPIA_10uMATP\\Quantification"
  F0: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211008_HeLa_CISD2_mtCEPIA_10uMATP\\F_over_F0"
constants:
  F0_start_time: 72
  F0_end_time: 92
# write null if you want to execute the script for all data files in your path
filename: "WT_6.nd2 - C=1_mtCEPIA_raw.xlsx"
sheetname: "Sheet1"