paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230203 HeLa CISD2 mtCEPIA3 linkers\\Quantification"
  F0: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230203 HeLa CISD2 mtCEPIA3 linkers\\F_over_F0"
constants:
  F0_start_time: 5
  F0_end_time: 25
# write null if you want to execute the script for all data files in your path
filename:
sheetname: "Sheet1"