paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\FDSS"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\FDSS\\Response"
constants:
  pacing: [1, 2, 3, 4]
  pacing_start: [0, 60, 180, 240]
  pacing_end: [60, 120, 240, 300]
  smoothing_constant: 4
  peak_threshold: 0.01
  
