paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\FDSS\\20220622_HeLaCISD2_test_magFluo-4_IP3_doseresponse\\F_over_F0"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\FDSS\\20220622_HeLaCISD2_test_magFluo-4_IP3_doseresponse\\Response"
constants:
  baseline_start_time_TG: 0
  baseline_end_time_TG: 20
  start_time_TG: 30
  end_time_TG: 70
  baseline_start_time_SOCE: 180
  baseline_end_time_SOCE: 200
  start_time_SOCE: 200
  end_time_SOCE: 240
  acquisition_time_interval: 1