paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211028_HeLaCISD2_ATP_dose_response\\Quantification"
  osc: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211028_HeLaCISD2_ATP_dose_response\\Quantification\\Results"
constants:
  smoothing_constant: 4
  stdev_non_oscillating_trace: 0.01
  peak_threshold: 0.06
  baseline_start: [20, 210, 430, 625, 920, 1258, 1625]
  baseline_end: [40, 230, 450, 645, 940, 1278, 1645]
  concentrations: ["0.0001uM ATP", "0.005uM ATP", "0.01uM ATP", "0.1uM ATP", "0.5uM ATP", "1uM ATP", "10uM ATP"]
  concentration_start: [30, 230, 450, 645, 940, 1278, 1645]
  concentration_end: [120, 320, 540, 735, 1030, 1368, 1735]
filename: "WT_2.nd2 - C=0_340_ratio.xlsx"
sheetname: "Sheet1"
Genotype: "WT"
ID: "20211028_WT_2"

