paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211202_HeLaCISD2_doseresponseATP\\Quantification"
  results: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211202_HeLaCISD2_doseresponseATP\\Quantification\\Results"
constants:
  smoothing_constant: 4
  stdev_non_oscillating_trace: 0.01
  peak_threshold: 0.06
  baseline_start: [50, 250, 425, 770, 995, 1240]
  baseline_end: [70, 270, 445, 790, 1015, 1260]
  concentrations: ["0.001uM ATP", "0.1uM ATP", "0.5uM ATP", "1uM ATP", "10uM ATP", "100uM ATP"]
  concentration_start: [73, 270, 446, 794, 1016, 1265]
  concentration_end: [163, 360, 536, 884, 1106, 1355]
filename: "WT_1.nd2 - C=0_340_ratio.xlsx"
sheetname: "Sheet1"
Genotype: "WT"
ID: "20211202_WT_1"

