paths:
  data: "C:\\Users\\jensl\\Box\\PhD\\Data\\NIKON\\20220408_mitoroGFP_HeLaCISD2\\Quantification"
  calibrated: "C:\\Users\\jensl\\Box\\PhD\\Data\\NIKON\\20220408_mitoroGFP_HeLaCISD2\\Calibrated"
  plots: "C:\\Users\\jensl\\Box\\PhD\\Data\\NIKON\\20220408_mitoroGFP_HeLaCISD2\\Calibrated"
constants:
  min_start_time: 1260
  min_end_time: 1780
  max_start_time: 150
  max_end_time: 1260
# write null if you want to execute the script for all data files in your path
filename: "mito_WT_3.nd2 - C=0_ratio.xlsx"
sheetname: "Sheet1"
