paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220616_HeLaCISD2_roGFP\\mito\\Quantification"
  calibrated: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220616_HeLaCISD2_roGFP\\mito\\Calibrated"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220616_HeLaCISD2_roGFP\\mito\\Calibrated"
constants:
  min_start_time: 935
  min_end_time: 1349
  max_start_time: 400
  max_end_time: 935
# write null if you want to execute the script for all data files in your path
filename: "WT_mito_ox_1.nd2 - C=0_ratio.xlsx"
