paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Quantification"
  calibrated: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Calibrated"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220408_HeLaCISD2_cytoroGFP\\Calibrated"
constants:
  min_start_time: 1324
  min_end_time: 1874
  max_start_time: 100
  max_end_time: 1324
# write null if you want to execute the script for all data files in your path
filename: "cyto_WT_4.nd2 - C=0_ratio.xlsx"
