paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220701_mitoroGFP_HeLaCISD2\\Traces"
  calibrated: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220701_mitoroGFP_HeLaCISD2\\Calibrated"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220701_mitoroGFP_HeLaCISD2\\Calibrated"
constants:
  min_start_time: 1140
  min_end_time: 1470
  max_start_time: 600
  max_end_time: 1140
# write null if you want to execute the script for all data files in your path
filename: "WT_3.nd2 - C=0_ratio.xlsx"
sheet_name: "Sheet1"