paths:
  data: "C:\\Users\\u0132307\\Desktop"
  calibrated: "C:\\Users\\u0132307\\Desktop"
  plots: "C:\\Users\\u0132307\\Desktop"
constants:
  example_bool: False
  min_start_time: 690
  min_end_time: 735
  max_start_time: 735
  max_end_time: 861
# write null if you want to exectute the script for all data files in your path
filename: "data.csv"
