paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220322_HeLaCISD2_store_content\\Quantification"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220322_HeLaCISD2_store_content\\Traces"
filename: Null
sheetname: "Sheet1"
