paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211202_HeLaCISD2_doseresponseATP\\Quantification"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211202_HeLaCISD2_doseresponseATP\\Traces"
filename: Null
sheetname: "Sheet1"
