paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210520-HeLaCISD2-FURA-Bcl2\\Multi_measure"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210520-HeLaCISD2-FURA-Bcl2\\Traces"

