paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\Multi_measure_transfected"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211119_HeLaCISD2_5uMATP_F4_mtCEPIA\\Traces"

