paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220617_HeLaCISD2_Bcl2_mtCEPIA\\Multi_measure"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20220617_HeLaCISD2_Bcl2_mtCEPIA\\Traces"