paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211008_HeLa_CISD2_mtCEPIA_10uMATP\\Multi_measure"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20211008_HeLa_CISD2_mtCEPIA_10uMATP\\Traces"

