paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210805_HeLaCISD2_FURA_RmtCEPIA3_store\\Multi_measure"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210805_HeLaCISD2_FURA_RmtCEPIA3_store\\Traces"

