paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20221006_HeLaCISD2_mtCEPIA_mutants\\Multi_measure_transfected"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20221006_HeLaCISD2_mtCEPIA_mutants\\Traces"