paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230213 HeLa CISD2 Bcl-2 OE\\Multi_measure"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230213 HeLa CISD2 Bcl-2 OE\\Traces"