paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210416-TrexCISD2-FURA-ER-store\\Quantification"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210416-TrexCISD2-FURA-ER-store\\Quantification\\IO_response"
constants:
  baseline_start_time: 298
  baseline_end_time: 318
  response_start_time: 438
  response_end_time: 528
filename: "KO_2_ratio.xlsx"
sheetname: "RM_no_baseline"