paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210401-Trex-CISD2-ER-store\\Quantification"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210401-Trex-CISD2-ER-store\\Quantification\\TG_response"
constants:
  baseline_start_time: 175
  baseline_end_time: 195
  response_start_time: 200
  response_end_time: 380
filename: "WT10-340-Results_ratio.xlsx"
sheetname: "Sheet1"