paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD"
  response: "C:\\Users\\u0132307\\Box Sync\\PhD\\Response"
constants:
  baseline_start_time: 40
  baseline_end_time: 60
  response_start_time: 65
  response_end_time: 100
filename: "Ctrl-6-ATP5-ER_raw.xlsx"
sheetname: "Sheet1"
