paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230213 HeLa CISD2 Bcl-2 OE\\Traces"
  time: "C:\\Users\\u0132307\\OneDrive - KU Leuven\\NIKON\\20230213_HeLaCISD2_Bcl2\\Time"
  results: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20230213 HeLa CISD2 Bcl-2 OE\\Quantification"
sheetname: "Sheet1"
