paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Confocal Zeiss\\20221206_HeLaCISD2_PM_mito\\Measure"
  results: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Confocal Zeiss\\20221206_HeLaCISD2_PM_mito\\Results"

