paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210225-TrexCISD2-FURA-RerCEPIA-Ca2+-WayneChen\\Quantification"
  SOICR: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210225-TrexCISD2-FURA-RerCEPIA-Ca2+-WayneChen\\Quantification\\FF0_SOICR"
constants:
  threshold_start_time: 245
  threshold_end_time: 305
  cut_off_percentage: 0.01
  tetracaine_start_time: 305
  tetracaine_end_time: 340
  caffeine_start_time: 343
  caffeine_end_time: 393
filename: "20210225-WT2.xlsx"
sheetname: "FF0"

